from admin.login import AdminLoginHandler, AdminRegisterHandler
from admin.edit_password import AdminEditPasswordHandler
from admin.user import AdminUserHandler
from admin.discount_type import AdminDiscountTypeHandler
from admin.discount import AdminDiscountHandler
from admin.user_discount_rel import AdminUserDiscountRelHandler
